
import type { ScoredNiche } from '../types';

const downloadFile = (content: string, fileName: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportSingleNicheBlueprint = (niche: ScoredNiche) => {
  const markdown = `
# 🚀 2025-2026 EXECUTION BLUEPRINT: ${niche.niche}
*Generated by Fiverr Niche Finder AI Intelligence v3.0*

---

## 💎 1. MARKET OPPORTUNITY OVERVIEW
- **Intelligence Score:** ${niche.score}/100
- **Market Dynamics:** Demand (${niche.demand}/10) | Resistance (${niche.competition}/10) | Momentum (${niche.trend.toFixed(2)})
- **Target Persona:** ${niche.targetAudience}
- **Value Proposition:** ${niche.description}

## ⚡ 2. THE COMPETITIVE BATTLE PLAN (2025/26)
- **The Gap (Competitor Weakness):** ${niche.competitorWeakness}
- **Tactical Disruption:** ${niche.battlePlan}
- **Competitive Landscape Note:** ${niche.competitionNote}

## 💰 3. FINANCIAL PROJECTIONS
- **Strategic Entry Price:** $${niche.averagePrice}
- **Value Tiers:**
  - Basic (Entry): $${Math.round(niche.averagePrice * 0.5)}
  - Standard (Scale): $${niche.averagePrice}
  - Premium (Authority): $${Math.round(niche.averagePrice * 1.8)}
- **Est. Platform Yield (80%):** $${(niche.averagePrice * 0.8).toFixed(2)}

## ✍️ 4. HIGH-CONVERSION GIG ASSETS
### Psychological Hook Titles:
${niche.gigTitles.map(t => `- [HOOK] ${t}`).join('\n')}

### Semantic Search Tags:
${niche.keywords.join(', ')}

### Transformation-Led Gig Copy:
${niche.gigDescription}

## 🛡️ 5. OBJECTION-SLAYER FAQS (HIGH TRUST)
${niche.faqs.map(f => `### Q: ${f.question}\n**THE CLOSER:** ${f.answer}`).join('\n\n')}

---
**CONFIDENTIAL STRATEGY DOCUMENT**
*Disclaimer: AI-generated projections based on real-time market grounding. Move with speed.*
  `.trim();

  downloadFile(markdown, `${niche.niche.toLowerCase().replace(/\s+/g, '_')}_blueprint.md`, 'text/markdown');
};

export const exportToCSV = (data: ScoredNiche[], fileName: string): boolean => {
  if (data.length === 0) return false;
  const columns = ['niche', 'score', 'averagePrice', 'demand', 'competition', 'trend', 'targetAudience', 'battlePlan'];
  const headers = columns.join(',');
  const rows = data.map(n => columns.map(c => `"${String((n as any)[c]).replace(/"/g, '""')}"`).join(','));
  downloadFile([headers, ...rows].join('\n'), fileName, 'text/csv');
  return true;
};

export const exportToJSON = (data: ScoredNiche[], fileName: string): boolean => {
  if (data.length === 0) return false;
  downloadFile(JSON.stringify(data, null, 2), fileName, 'application/json');
  return true;
};
